// <auto-generated />
namespace GestionPresencesProfesseursISI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class creation_db_gestion_presence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creation_db_gestion_presence));
        
        string IMigrationMetadata.Id
        {
            get { return "202503051643578_creation_db_gestion_presence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
